### ISSUE TITLE
Uncaught exception on await Character.items(): KeyError

### ISSUE THREAD

**Issue by ElReyZero** [leonhard-s/auraxium#58] opened 2022-10-06 20:43 UTC
## Bug
Exception raised when trying to retrieve a character's items

### Current Behavior:
Exception when awaiting a character's items

### Expected Behavior:
The function should return the requested character's items

### Steps To Reproduce:
1. Set up the auraxium client
2. Get a character by name or id
3. Try to do `await char.items()`

### Code example
    import auraxium
    from auraxium import ps2
    import asyncio

    async def main():
        async with auraxium.Client() as client:

        char = await client.get_by_name(ps2.Character, 'ElReyZero')
        items = await char.items()
        print(items)

    asyncio.run(main())

### Full Traceback:
Traceback (most recent call last):
  File "d:\Users\User\Documents\testing.py", line 29, in <module>
    asyncio.run(main())
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "d:\Users\User\Documents\testing.py", line 11, in main
    print(await char.items())
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\site-packages\auraxium\_proxy.py", line 168, in flatten
    return [e async for e in self]
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\site-packages\auraxium\_proxy.py", line 168, in <listcomp>
    return [e async for e in self]
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\site-packages\auraxium\_proxy.py", line 153, in __anext__
    await self._poll()
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\site-packages\auraxium\_proxy.py", line 71, in _poll
    list_ = self._resolve_nested_payload(payload)
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\site-packages\auraxium\_proxy.py", line 129, in _resolve_nested_payload
    data.extend(resolve_join(join, parent))
  File "D:\Users\User\AppData\Roaming\Python\Python310\lib\site-packages\auraxium\_proxy.py", line 106, in resolve_join
    value = element[f'{on_}_join_{join.data.collection}']
KeyError: 'item_id_join_item'

3.11 Traceback: https://pastebin.com/kpz1SpWL

### Environment:
- OS: Windows 11
- Python 3.10.2
- Auraxium Version 0.2.2

**Comment by leonhard-s** [comment] 2022-10-07 21:15
Hi, thanks for the report.

I am unable to reproduce this issue with any of my characters - do you happen to have a character name or ID for which this occured?

I suspect that this may be related to a character that is either very new or deleted (or otherwise bad data), these may not have an entry in the `characters_item` collection, causing this error.

**Comment by ElReyZero** [comment] 2022-12-04 01:21
Sorry for the late response. I'm getting the error even with every character I try be it new or old. All of those are active characters

**Comment by leonhard-s** [comment] 2022-12-12 18:21
There is unfortunately not a lot I can do without being able to repro the issue. Could you share more details about your platform, Auraxium version, or an MRE?

**Comment by ElReyZero** [comment] 2022-12-12 18:41
I tried with Python 3.10.2. 3.10.5 and 3.11.0
Auraxium version is 0.2.2
OS: Windows 11

Since Python 3.11 has a better traceback error, here's what I'm getting:

### Traceback:
https://pastebin.com/kpz1SpWL

**Comment by leonhard-s** [comment] 2023-03-05 10:26
Resolved in [0.2.3](https://github.com/leonhard-s/auraxium/releases/tag/v0.2.3).

**Closed by leonhard-s** 2023-03-05 10:26 UTC
Labels: bug, question
